# Generated by Django 3.1.7 on 2021-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICUModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icu_name', models.CharField(max_length=255)),
                ('total_ventilator', models.IntegerField(default=0, max_length=255)),
                ('ventilator_left', models.IntegerField(default=0, max_length=255)),
                ('total_unventilator', models.IntegerField(default=0, max_length=255)),
                ('unventilator_left', models.IntegerField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IsolationRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('total_room', models.IntegerField(default=0, max_length=255)),
                ('room_left', models.IntegerField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=255)),
                ('total_ventilator', models.IntegerField(default=0, max_length=255)),
                ('ventilator_left', models.IntegerField(default=0, max_length=255)),
            ],
        ),
    ]
