# Generated by Django 3.1.7 on 2021-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icumodels',
            name='total_unventilator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='icumodels',
            name='total_ventilator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='icumodels',
            name='unventilator_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='icumodels',
            name='ventilator_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='isolationroom',
            name='room_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='isolationroom',
            name='total_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialroom',
            name='total_ventilator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialroom',
            name='ventilator_left',
            field=models.IntegerField(default=0),
        ),
    ]
