# Generated by Django 3.1.7 on 2021-07-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210713_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isolationroom',
            old_name='room_left',
            new_name='bed_left',
        ),
        migrations.RenameField(
            model_name='isolationroom',
            old_name='total_room',
            new_name='total_bed',
        ),
    ]
